Fix javadoc missing bug (#1018)
Fixes https://github.com/streamnative/kop/issues/1015

# Motivation

Fix upload rule failure during the release process:

```
Error:  Rule failure while trying to close staging repository with ID "iostreamnative-1043".
Error:  
Error:  Nexus Staging Rules Failure Report
Error:  ==================================
Error:  
...
          Missing: no javadoc jar found in folder
...
```