[improve] Add message.max.bytes for describe broker config (#1776)
### Motivation

Some of the Producer requires the `message.max.bytes` configuration.
```
Error: [CDC:ErrKafkaNewSaramaProducer]new sarama producer: [CDC:ErrKafkaBrokerConfigNotFound]cannot find the `message.max.bytes` from the broker's configuration

```

### Modifications

* Add `message.max.bytes` for describe broker config. The config is
reused pulsar config.

(cherry picked from commit 92285f18f7b3afc5bfeec5fccba27f9ae095369d)