[branch-2.8.3] Fix branch 2.8.3 KafkaMockAuthorizationProvider compilation error (#1232)
### Motivation

The 2.8.3 branch's AuthorizationProvider has an abstract method `initialize`, which is changed to the default method in the future. 

We need to implement this method in the 2.8.3 branch to fix the compilation error.
```
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/kop/kop/tests/src/test/java/io/streamnative/pulsar/handlers/kop/security/auth/KafkaMockAuthorizationProvider.java:[35,8] io.streamnative.pulsar.handlers.kop.security.auth.KafkaMockAuthorizationProvider is not abstract and does not override abstract method initialize(org.apache.pulsar.broker.ServiceConfiguration,org.apache.pulsar.broker.cache.ConfigurationCacheService) in org.apache.pulsar.broker.authorization.AuthorizationProvider
```
See: https://github.com/streamnative/kop/runs/6000118135?check_suite_focus=true#step:5:890