Remove usage of Scala classes from Kafka in tests (#1653)
### Motivation

`KStreamAggregationTest` uses a Scala class `ConsoleConsumer`, which
might lead to a `NoClassDefFoundError` in branch-2.10:
https://github.com/streamnative/kop/actions/runs/3797937683/jobs/6459789362

### Modifications

Replace the `ConsoleConsumer` use with a `KafkaConsumer` and the same
formatting logic on each received record.

(cherry picked from commit 88120f6aef1ff346cb788ab9cb7a2ac687735630)